import Foundation

/// Tool to generate a HackerOne-style submission report.
struct GenerateSubmissionTool: Tool {
    var name: String { "generate_submission" }
    var description: String { "Generates a professional markdown vulnerability report (HackerOne style) from raw findings. Saves to local artifact directory." }
    var usageSchema: String { "generate_submission(title=\"<title>\", finding=\"<raw_finding_text>\", severity=\"<Low|Medium|High|Critical>\")" }
    var requiresPermission: Bool { true }
    var shouldCachePermission: Bool { true }
    
    func run(arguments: [String : String]) async throws -> ToolResult {
        guard let title = arguments["title"], let finding = arguments["finding"] else {
             return ToolResult(output: "Error: Missing 'title' or 'finding'.", isError: true)
        }
        let severity = arguments["severity"] ?? "Medium"
        
        let report = """
        # 🛡️ Vulnerability Report: \(title)
        
        **Date**: \(Date())
        **Severity**: **\(severity.uppercased())**
        **Status**: Verified (Automated Proof)
        
        ---
        
        ## 1. Summary
        Helix Agent verified a vulnerability in the target application.
        
        ## 2. Technical Details / Finding
        \(finding)
        
        ## 3. Impact
        (Contextual Analysis)
        - Confidentiality: High (Potential data leak)
        - Integrity: Moderate (Potential state modification)
        - Availability: Low
        
        This vulnerability allows an attacker to... (Agent to fill in logic here)
        
        ## 4. Steps to Reproduce
        1. Open the target URL.
        2. Execute the verified payload.
        3. Observe the result (as shown in Proof).
        
        ## 5. Remediation
        - **Input Validation**: Sanitize all user inputs.
        - **Output Encoding**: Encode data before rendering to HTML (for XSS).
        - **Access Control**: Verify user ownership of objects (for IDOR).
        
        ---
        *Generated by Helix Agent (Pro Mode)*
        """
        
        let filename = title.lowercased().replacingOccurrences(of: " ", with: "_") + "_report.md"
        
        // Resolve an app-specific artifacts directory under Application Support
        let fm = FileManager.default
        let base = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first ?? fm.homeDirectoryForCurrentUser
        let artifactsDir = base.appendingPathComponent("HelixAgent/Artifacts", isDirectory: true)
        try? fm.createDirectory(at: artifactsDir, withIntermediateDirectories: true)
        
        let path = artifactsDir.appendingPathComponent(filename).path
        
        let writeResult = try await WriteFileTool().run(arguments: ["path": path, "content": report])
        
        if writeResult.isError {
             return ToolResult(output: "Failed to save report: \(writeResult.output)", isError: true)
        }
        
        return ToolResult(output: "✅ Report generated successfully: [\(filename)](\(path))", isError: false)
    }
}
